exports.modules = [
  { route: "auth" },
  {
    route: "availabilities",
    model: "availability",
    collectionName: "Availability",
  },
  { route: "blogs", model: "blog", collectionName: "Blog" },
  { route: "bonuses", model: "bonus", collectionName: "Bonus" },
  { route: "books", model: "book", collectionName: "Book" },
  { route: "branches", model: "branch", collectionName: "Branch" },
  {
    route: "certificates",
    model: "certificate",
    collectionName: "Certificate",
  },
  { route: "company", model: "company", collectionName: "Company" },
  { route: "contacts" },
  {
    route: "conversations",
    model: "conversation",
    collectionName: "Conversation",
  },
  { route: "feedbacks", model: "feedback", collectionName: "Feedback" },
  { route: "files" },
  { route: "groups", model: "group", collectionName: "Group" },
  { route: "homeworks", model: "homework", collectionName: "Homework" },
  { route: "hwtasks", model: "hwtask", collectionName: "Hwtask" },
  { route: "inventories", model: "inventory", collectionName: "Inventory" },
  { route: "lessons", model: "lesson", collectionName: "Lesson" },
  {
    route: "lower-categories",
    model: "lowerCategory",
    collectionName: "LowerCategory",
  },
  {
    route: "placement-meeting-results",
    model: "placementMeetingResult",
    collectionName: "PlacementMeeting",
  },
  {
    route: "placement-meetings",
    model: "placementMeeting",
    collectionName: "PlacementMeetingResult",
  },
  { route: "programs", model: "program", collectionName: "Program" },
  { route: "recurrences", model: "recurrence", collectionName: "Recurrence" },
  { route: "rooms", model: "room", collectionName: "Room" },
  { route: "sales", model: "sale", collectionName: "Sale" },
  { route: "teacher" },
  {
    route: "transactions",
    model: "transaction",
    collectionName: "Transaction",
  },
  {
    route: "upper-categories",
    model: "upperCategory",
    collectionName: "UpperCategory",
  },
  { route: "users", model: "user", collectionName: "User" },
  { route: "enrollments", model: "enrollment", collectionName: "Enrollment" },
  {
    route: "notifications",
    model: "notification",
    collectionName: "Notification",
  },
];
